### ISSUE TITLE
Generate code from proto files included in the image

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/docker-protobuf#12]
The docker image contains various proto files which are dependencies (`gogoproto/gogo.proto`, `protoc-gen-swagger/options/annotations.proto`) for Jaeger's `model.proto` and services like `query.proto`... 

The code generation to various languages works fine. However the generated code requires dependencies on the included proto dependencies as these are not generated (they are just used by `protoc` at the generation phase) so the code fails at runtime on missing symbols. The problem is that there are no official `jars` (or packages in other languages).

To make the generated code work in Java I had to add these dependencies:
```xml
    <!-- fix missing symbols GoGoProtos -->
    <dependency>
      <groupId>com.github.QubitProducts</groupId>
      <artifactId>gogoproto-java</artifactId>
      <version>1.0.0</version>
    </dependency>
    <!--  fix missing class grpc.gateway.protoc_gen_swagger.options.Annotations  -->
    <dependency>
      <groupId>org.apache.skywalking</groupId>
      <artifactId>receiver-proto</artifactId>
      <version>6.6.0</version>
      <exclusions>
        <exclusion>
          <artifactId>*</artifactId>
          <groupId>*</groupId>
        </exclusion>
      </exclusions>
    </dependency>
```
More in https://github.com/jaegertracing/jaeger-analytics-java/pull/34#issuecomment-597783176

**Comment by annanay25** [comment]
The community also suggests to generate the files each time. https://github.com/grpc-ecosystem/grpc-gateway/issues/794#issuecomment-434966177

**Comment by pavolloffay** [comment]
As the proto dependencies are in the image I was able to generate code and remove jars

```
	$(PROTOC) \
		$(PROTO_INCLUDES) \
		--java_out=$(PWD)/proto/src/main/java /usr/include/protoc-gen-swagger/options/openapiv2.proto

	$(PROTOC) \
		$(PROTO_INCLUDES) \
		--java_out=$(PWD)/proto/src/main/java /usr/include/github.com/gogo/protobuf/gogoproto/gogo.proto
```

I will submit a PR to the readme to document this.
