### ISSUE TITLE
Rebase with the latest upstream

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/docker-protobuf#17]
This repository was originally forked from [TheThingsIndustries/docker-protobuf](https://github.com/TheThingsIndustries/docker-protobuf), which has included many improvements to the builder, including support for more languages and newest gRPC versions. The gRPC version bump alone would be a welcome change (see jaegertracing/jaeger#2443), as it's not simply a version change: apparently, the way the gRPC binaries are built has changed significantly.

It appears as well that C# has been supported upstream, which might be enough for us to remove our custom C# builder. Input from @Falco20019 is required here to confirm this is the case.

**Comment by jpkrohling** [comment]
Related to jaegertracing/jaeger#2449

**Comment by Falco20019** [comment]
Right now, all but C# use 1.26.0 and we need 1.28.1 at least. Since #18 seem to intend to raise `GRPC_VERSION` for all to `1.31.0`, we should be fine on C#!

**Comment by jpkrohling** [comment]
@Falco20019 does it mean that we can remove the C#-specific parts from the build?

**Comment by Falco20019** [comment]
@jpkrohling As long as you use 1.28.1+, you can definitely remove it. It was only necessary to build C# with at least this version and we had the requirement to not update all other versions. Once all want to use 1.31.0 anyway, we are safe again :)
