### ISSUE TITLE
Add CI workflow to validate generated Docker image against other Jaeger repos

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/docker-protobuf#30]
Right now we don't have any validation that any changes to the image will not break the repos where it is consumed, namely `jaeger` and `jaeger-idl`.

Proposal: Add a CI workflow that will check out those repos as part of the CI, and run their proto build steps using the new version of the image. This may involve tweaking their Makefiles to allow overriding image version (but may already be supported, needs to be verified).

**Comment by akagami-harsh** [comment]
working on this !!
