### ISSUE TITLE
Add ARM64 architecture to the Docker image

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/docker-protobuf#31]
Currently the image built here cannot be used on Macs that use Apple hardware, because the image is only built for amd64 architecture. It would be great to extent this to include arm64, similar to how we build multi-arch images in Jaeger.

**Comment by Wh1isper** [comment]
Maybe use docker `buildx` to support multiple platforms? Do you think it's better to cross-compile or use QEMU emulation?

I can help with cross-platform image builds using buildx (based on QEMU emulation): 
https://github.com/Wh1isper/docker-protobuf/blob/feature-upgrade/.github/workflows/wh1isper-dockerimage.yml#L32

**Comment by yurishkuro** [comment]
I don't have a preference. For Jaeger binaries we are using cross-compiling and buildx, I don't know which is better for the protobuf. Did you test the workflow that you linked?

**Comment by yurishkuro** [comment]
Also, I am not a big fan of using `docker/build-push-action@v4`, because it means I cannot reproduce the build locally, only in a GH workflow.

**Comment by Wh1isper** [comment]
@yurishkuro Understood, I'm going to try to build a cross-platform image with `buildx`, and if it's works, I will submit a PR.

The workflow I linked to can build amd64 image for testing this pr: https://github.com/jaegertracing/jaeger-idl/pull/101 (Forgive the scribbling on this job.)

**Comment by Wh1isper** [comment]
Some feedback https://github.com/jaegertracing/docker-protobuf/pull/32:
- QEMU builds are too slow and exceed the limits of github action. 
- It took about 3.5 hours to build the ARM64 image on my 7700hq (4c8t32g), and as far as I know github action provides resources for 2c4g, FYI

It may require a modification to the dockerfile, which I don't have time to delve into at the moment. So.. If anyone would like to continue this work, they can also seek my help 🙂

**Comment by yurishkuro** [comment]
Solved in #36 or maybe even earlier
