### ISSUE TITLE
[tracking] Integrate GitHub actions and use jaegertracing dockerhub/quay account 

### ISSUE THREAD

**Issue by annanay25** [jaegertracing/docker-protobuf#5]
- [ ] Integrate with GitHub actions
- [ ] As of #4, the project uses `annanay25:jaeger-docker-protobuf:latest` image. Move to the jaegertracing user on dockerhub/quay

**Comment by yurishkuro** [comment]
I set up https://hub.docker.com/repository/docker/jaegertracing/protobuf/

It is "connected" to github so that Docker Hub can build automatically on pushes to master. Is there an extra benefit of using GitHub Actions?

**Comment by annanay25** [comment]
@yurishkuro - Naming/tagging isn't supported through the Dockerfile https://stackoverflow.com/a/38986676

**Comment by yurishkuro** [comment]
You don't do it via Dockerfile, it's done on Docker Hub. For example, I have https://hub.docker.com/r/yurishkuro/microsim/tags, which is auto-built from the repo https://github.com/yurishkuro/microsim

**Comment by yurishkuro** [comment]
I am having trouble configuring auto-builds in this new DockerHub repo, their UI is ridiculous. It doesn't let me select the jaegertracing organization.

So perhaps easier to go with normal publishing, either from Travis or GH Actions.

**Comment by annanay25** [comment]
Okay sure.
